### ISSUE TITLE
SVG preview glitches

### ISSUE THREAD

**Issue by aVandalInShorts** [Solutions-Nitriques/image_preview#9]
When you save the entry with a big svg it has to unwanted effects:

1. When it's too wide and in the aside section, the hole column goes under the main column. The image could be in the need of a "max-width: 100%"?
1. It doesn't have a max-height eighter. So it takes a lot of place if the image is tall.

**Comment by nitriques** [comment]
Do you have a screenshot ?

**Comment by aVandalInShorts** [comment]
In the main section: 
![svg-bug-main](https://cloud.githubusercontent.com/assets/5823666/8306860/2c8ee512-1989-11e5-89f0-fe6aaa700877.jpg)

In the sidebar section:
![svg-bug](https://cloud.githubusercontent.com/assets/5823666/8306863/389a6304-1989-11e5-85cb-edcce62641c7.jpg)

**Comment by nitriques** [comment]
Ooo ok, I'll fix this. Thanks.

**Comment by nitriques** [comment]
Fixed in bdc55726f70eab4a3e4acd9664a75eac8a036f30
